import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/main/Navbar/Navbar";
import Footer from "@/components/main/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BATP - Behavior Analysis & Therapy Partners",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo2.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
   <Navbar/>
        
        {children}
        <Footer/>
        </body>
    </html>
  );
}
